# Generated by Django 6.0.5 on 2026-05-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Commerce Platform', max_length=255)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('timezone', models.CharField(default='Europe/Paris', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StoreSettings',
        ),
    ]
